Adding difference between dev and prod for rethinkdb

diff --git a/kube-rethinkdb/rethinkdb-statefulset.yml b/kube-rethinkdb/rethinkdb-statefulset.yml
--- a/kube-rethinkdb/rethinkdb-statefulset.yml
+++ b/kube-rethinkdb/rethinkdb-statefulset.yml
@@ -59,16 +59,27 @@ spec:
           <<: *healthcheck
 
       #RethinkDB node sidecar
-      - image: python
+      - image: beevelop/nodejs-python-ruby 
         imagePullPolicy: Always
         name: rethinkdb-sidecar
         command:
         - /bin/sh
         - -ec
         - |
-          pip install rethinkdb
           LATEST_DUMP=$(ls -Art /mnt/tylt-rethink-prod/*.tar.gz | tail -n1)
-          /usr/local/bin/rethinkdb-restore $LATEST_DUMP -c localhost:28015 --clients 16 || echo "Restore Failed"
+
+          if [ "PRODUCTION_VAR" -eq "false" ]; then
+            npm install -g recli
+            recli --host localhost --port 28015 'r.dbCreate("tyltInbox")' || echo $?
+            recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("messages_twitter")' || echo $?
+            recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("messages_facebook")' || echo $?
+            recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("polls_facebook")' || echo $?
+            recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("manual_votes")' || echo $?
+          else
+            pip install rethinkdb
+            /usr/local/bin/rethinkdb-restore $LATEST_DUMP -c localhost:28015 --clients 16 || echo "Restore Failed"
+          fi
+
           while [ 1 -eq 1 ]; do sleep 10; done
         envFrom:
         - configMapRef:
