Forcing if tables exists

diff --git a/kube-rethinkdb/rethinkdb-statefulset.yml b/kube-rethinkdb/rethinkdb-statefulset.yml
--- a/kube-rethinkdb/rethinkdb-statefulset.yml
+++ b/kube-rethinkdb/rethinkdb-statefulset.yml
@@ -77,7 +77,7 @@ spec:
 
           if [ "$NAMESPACE" = "devint" ] || [ "$NAMESPACE" = "production" ]; then
             pip install rethinkdb
-            /usr/local/bin/rethinkdb-restore $LATEST_DUMP -c localhost:28015 --clients 16 #|| echo "Restore Failed"
+            /usr/local/bin/rethinkdb-restore $LATEST_DUMP -c localhost:28015 --clients 16 --force #|| echo "Restore Failed"
           else
             npm install -g recli
             recli --host localhost --port 28015 'r.dbCreate("tyltInbox")' || echo $?
